import React, { createContext, useState, useEffect, useContext } from 'react';
import { getUserProfile, updateUserProfile } from '../services/api';

const LanguageContext = createContext();

const translations = {
    'pt-BR': {
        // Common
        'common.save': 'Salvar',
        'common.cancel': 'Cancelar',
        'common.delete': 'Excluir',
        'common.edit': 'Editar',
        'common.search': 'Buscar',
        'common.loading': 'Carregando...',
        'common.saving': 'Salvando...',
        'common.close': 'Fechar',
        'common.confirm': 'Confirmar',
        'common.yes': 'Sim',
        'common.no': 'Não',
        
        // Navigation
        'nav.dashboard': 'Painel',
        'nav.appointments': 'Atendimentos',
        'nav.patients': 'Pacientes',
        'nav.clinics': 'Clínicas',
        'nav.reports': 'Relatórios',
        'nav.profile': 'Perfil',
        
        // Dashboard
        'dashboard.title': 'Painel Geral',
        'dashboard.subtitle': 'Visão geral do desempenho da sua clínica.',
        'dashboard.monthlyRevenue': 'Faturamento do Mês',
        'dashboard.received': 'Recebido',
        'dashboard.pending': 'Pendente',
        'dashboard.appointments': 'Atendimentos',
        'dashboard.totalProcedures': 'Total de procedimentos realizados',
        'dashboard.clinics': 'Clínicas Cadastradas',
        'dashboard.activePartners': 'Parceiros ativos',
        'dashboard.averageTicket': 'Ticket Médio',
        'dashboard.perAppointment': 'Por atendimento',
        'dashboard.weeklyProductivity': 'Produtividade Semanal',
        'dashboard.finishedVsPending': 'Atendimentos finalizados vs pendentes',
        'dashboard.clinicRanking': 'Ranking de Clínicas',
        'dashboard.byRevenue': 'Ordenado por faturamento',
        'dashboard.viewAll': 'Ver todas',
        'dashboard.newAppointment': 'Novo Atendimento',
        'dashboard.export': 'Exportar',
        'dashboard.finished': 'Finalizados',
        
        // Appointments
        'appointments.title': 'Atendimentos',
        'appointments.subtitle': 'Gerencie seus procedimentos e agendamentos.',
        'appointments.newAppointment': 'Novo Atendimento',
        'appointments.editAppointment': 'Editar Atendimento',
        'appointments.totalReceived': 'Total Recebido',
        'appointments.pendingValue': 'Valor Pendente',
        'appointments.totalAppointments': 'Total de Atendimentos',
        'appointments.filterAll': 'Todos',
        'appointments.filterPaid': 'Pagos',
        'appointments.filterPending': 'Pendentes',
        'appointments.filterScheduled': 'Agendados',
        'appointments.searchPlaceholder': 'Buscar por nome, clínica ou procedimento...',
        'appointments.patient': 'Paciente',
        'appointments.procedure': 'Procedimento',
        'appointments.dateTime': 'Data & Hora',
        'appointments.clinic': 'Clínica',
        'appointments.value': 'Valor',
        'appointments.status': 'Status',
        'appointments.paid': 'Pago',
        'appointments.pending': 'Pendente',
        'appointments.scheduled': 'Agendado',
        'appointments.unknown': 'Desconhecido',
        'appointments.noAppointments': 'Nenhum atendimento encontrado',
        'appointments.tryFilters': 'Tente ajustar os filtros ou crie um novo atendimento.',
        'appointments.clinicRequired': 'Clínica *',
        'appointments.selectClinic': 'Selecione uma clínica',
        'appointments.appointmentDate': 'Data do Atendimento',
        'appointments.time': 'Horário *',
        'appointments.patientName': 'Nome do Paciente *',
        'appointments.phone': 'Telefone',
        'appointments.email': 'E-mail',
        'appointments.procedureRequired': 'Procedimento *',
        'appointments.selectProcedure': 'Selecione um procedimento',
        'appointments.other': 'Outros',
        'appointments.specifyProcedure': 'Especifique o procedimento *',
        'appointments.procedurePlaceholder': 'Digite o nome do procedimento',
        'appointments.procedureAutoSave': 'Este procedimento será salvo automaticamente para uso futuro.',
        'appointments.valueRequired': 'Valor *',
        'appointments.currency': 'Moeda',
        'appointments.paymentType': 'Tipo de Recebimento',
        'appointments.percentage': 'Porcentagem (%)',
        'appointments.totalValue': 'Valor Total:',
        'appointments.percentageValue': 'Porcentagem:',
        'appointments.amountToReceive': 'Valor a Receber:',
        'appointments.paymentMade': 'Pagamento realizado?',
        'appointments.paymentDate': 'Data do Pagamento *',
        'appointments.paymentDateHint': '(Quando o dinheiro foi recebido)',
        'appointments.paymentDateExample': 'Ex: Se o atendimento foi em janeiro mas o pagamento veio em fevereiro (dia 10), informe a data de fevereiro aqui.',
        'appointments.clinicalEvolution': 'Evolução Clínica',
        'appointments.clinicalEvolutionPlaceholder': 'Descreva a evolução clínica do paciente...',
        'appointments.notes': 'Observações',
        'appointments.notesPlaceholder': 'Observações adicionais...',
        'appointments.radiographs': 'Radiografias',
        'appointments.uploadRadiographs': 'Clique para fazer upload de radiografias',
        'appointments.selectFiles': 'Selecionar Arquivos',
        'appointments.uploading': 'Enviando...',
        'appointments.filesSelected': 'arquivo(s) selecionado(s):',
        'appointments.remove': 'Remover',
        'appointments.saveAppointment': 'Salvar Atendimento',
        'appointments.saveChanges': 'Salvar Alterações',
        'appointments.cancel': 'Cancelar',
        'appointments.deleteConfirm': 'Tem certeza que deseja excluir este atendimento?',
        'appointments.deleteSuccess': 'Atendimento excluído com sucesso!',
        'appointments.saveSuccess': 'Atendimento salvo com sucesso!',
        'appointments.saveError': 'Erro ao salvar atendimento',
        'appointments.deleteError': 'Erro ao excluir atendimento',
        'appointments.invalidImage': 'não é uma imagem válida.',
        'appointments.fileTooLarge': 'é muito grande (máx: 10MB).',
        'appointments.filesSelectedSuccess': 'arquivo(s) selecionado(s) com sucesso!',
        'appointments.processFilesError': 'Erro ao processar arquivos',
        'appointments.radiographsError': 'Atendimento salvo, mas houve erro ao salvar algumas radiografias',
        'appointments.procedureError': 'Erro ao criar procedimento. Usando o nome digitado.',
        'appointments.received': 'Recebido:',
        
        // Patients
        'patients.title': 'Pacientes',
        'patients.subtitle': 'Gerencie seus pacientes e históricos.',
        'patients.newPatient': 'Novo Paciente',
        'patients.totalPatients': 'Total de Pacientes',
        'patients.totalAppointments': 'Total de Atendimentos',
        'patients.foundRecords': 'Registros Encontrados',
        'patients.searchPlaceholder': 'Buscar por nome, email ou telefone...',
        'patients.lastVisit': 'Última visita',
        'patients.noPatients': 'Nenhum paciente encontrado',
        'patients.trySearch': 'Tente uma busca diferente ou cadastre um novo paciente.',
        'patients.loading': 'Carregando pacientes...',
        'patients.fullName': 'Nome Completo *',
        'patients.email': 'E-mail',
        'patients.phone': 'Telefone',
        'patients.savePatient': 'Salvar Paciente',
        'patients.createError': 'Erro ao criar paciente',
        
        // Clinics
        'clinics.title': 'Clínicas',
        'clinics.subtitle': 'Gerencie suas clínicas parceiras.',
        'clinics.newClinic': 'Nova Clínica',
        'clinics.totalClinics': 'Total de Clínicas',
        'clinics.activeClinics': 'Clínicas Ativas',
        'clinics.totalRevenue': 'Faturamento Total',
        'clinics.searchPlaceholder': 'Buscar clínica...',
        'clinics.name': 'Nome',
        'clinics.address': 'Endereço',
        'clinics.contact': 'Contato',
        'clinics.phone': 'Telefone',
        'clinics.email': 'E-mail',
        'clinics.status': 'Status',
        'clinics.active': 'Ativa',
        'clinics.inactive': 'Inativa',
        'clinics.noClinics': 'Nenhuma clínica encontrada',
        'clinics.trySearch': 'Tente uma busca diferente ou cadastre uma nova clínica.',
        'clinics.totalAppointments': 'Total de Atendimentos',
        'clinics.appointments': 'Atendimentos',
        'clinics.averageTicket': 'Ticket Médio Geral',
        'clinics.ticketAverage': 'Ticket Médio',
        'clinics.registerNew': 'Cadastre uma nova clínica para começar.',
        'clinics.clinicName': 'Nome da Clínica',
        'clinics.clinicNameExample': 'Ex: Clínica Sorriso',
        'clinics.addressPlaceholder': 'Rua, Número, Cidade',
        'clinics.edit': 'Editar',
        'clinics.delete': 'Excluir',
        
        // Reports
        'reports.title': 'Relatórios',
        'reports.subtitle': 'Análise financeira e de produtividade',
        'reports.exportPDF': 'Exportar PDF',
        'reports.revenueReceived': '💰 Receita Recebida',
        'reports.servicesRendered': '📅 Serviços Prestados',
        'reports.receivedInPeriod': '💰 Recebido no período',
        'reports.renderedInPeriod': '📅 Prestado no período',
        'reports.averageTicket': 'Ticket Médio',
        'reports.perAppointment': 'Por atendimento',
        'reports.totalAppointments': 'Total Atendimentos',
        'reports.receivedVsPending': 'Recebido vs. Pendente',
        'reports.comparativeValues': 'Comparativo de valores no período',
        'reports.clinicDistribution': 'Distribuição por Clínica',
        'reports.percentageAndValues': 'Percentual e valores faturados',
        'reports.recentAppointments': 'Atendimentos Recentes',
        'reports.lastProcedures': 'Últimos procedimentos realizados',
        'reports.noAppointments': 'Nenhum atendimento encontrado no período selecionado.',
        
        // Profile
        'profile.title': 'Perfil e Configurações',
        'profile.subtitle': 'Gerencie sua conta e preferências',
        'profile.activePlan': 'Plano Ativo',
        'profile.signOut': 'Sair',
        'profile.personalInfo': 'Informações Pessoais',
        'profile.fullName': 'Nome Completo',
        'profile.email': 'E-mail',
        'profile.phone': 'Telefone',
        'profile.saveChanges': 'Salvar Alterações',
        'profile.preferences': 'Preferências',
        'profile.language': 'Idioma',
        'profile.currency': 'Moeda',
        'profile.theme': 'Tema',
        'profile.darkMode': 'Modo Noturno',
        'profile.lightMode': 'Modo Claro',
        'profile.autoMode': 'Automático',
        'profile.darkModeDescription': 'Interface com cores escuras',
        'profile.lightModeDescription': 'Interface com cores claras',
        'profile.autoModeDescription': 'Segue a preferência do sistema/navegador',
        'profile.savePreferences': 'Salvar Preferências',
        
        // Login
        'login.title': 'Bem-vindo de volta!',
        'login.subtitle': 'Entre na sua conta para continuar',
        'login.email': 'E-mail',
        'login.password': 'Senha',
        'login.signIn': 'Entrar',
        'login.forgotPassword': 'Esqueceu sua senha?',
        
        // Errors and Alerts
        'error.generic': 'Ocorreu um erro',
        'error.save': 'Erro ao salvar',
        'error.delete': 'Erro ao excluir',
        'error.load': 'Erro ao carregar',
        'error.create': 'Erro ao criar',
        'error.update': 'Erro ao atualizar',
        'error.unauthorized': 'Usuário não autenticado',
        'error.notFound': 'Registro não encontrado',
        'error.network': 'Erro de conexão. Verifique sua internet.',
        'error.fileUpload': 'Erro ao fazer upload do arquivo',
        'error.fileTooLarge': 'Arquivo muito grande',
        'error.invalidFile': 'Arquivo inválido',
        'error.invalidImage': 'Por favor, selecione apenas arquivos de imagem.',
        'error.maxFileSize': 'O arquivo é muito grande. Tamanho máximo: 10MB.',
        'error.processingFile': 'Erro ao processar arquivo',
        'error.deleteConfirm': 'Tem certeza que deseja excluir?',
        'error.deletePatientConfirm': 'Tem certeza que deseja excluir este paciente? Todos os atendimentos relacionados também serão excluídos.',
        'error.deleteRadiographConfirm': 'Tem certeza que deseja excluir esta radiografia?',
        'success.save': 'Salvo com sucesso!',
        'success.delete': 'Excluído com sucesso!',
        'success.create': 'Criado com sucesso!',
        'success.update': 'Atualizado com sucesso!',
        'success.upload': 'Upload realizado com sucesso!',
        'success.settingsSaved': 'Configurações salvas com sucesso!',
    },
    'en-US': {
        // Common
        'common.save': 'Save',
        'common.cancel': 'Cancel',
        'common.delete': 'Delete',
        'common.edit': 'Edit',
        'common.search': 'Search',
        'common.loading': 'Loading...',
        'common.saving': 'Saving...',
        'common.close': 'Close',
        'common.confirm': 'Confirm',
        'common.yes': 'Yes',
        'common.no': 'No',
        
        // Navigation
        'nav.dashboard': 'Dashboard',
        'nav.appointments': 'Appointments',
        'nav.patients': 'Patients',
        'nav.clinics': 'Clinics',
        'nav.reports': 'Reports',
        'nav.profile': 'Profile',
        
        // Dashboard
        'dashboard.title': 'Dashboard',
        'dashboard.subtitle': 'Overview of your clinic performance.',
        'dashboard.monthlyRevenue': 'Monthly Revenue',
        'dashboard.received': 'Received',
        'dashboard.pending': 'Pending',
        'dashboard.appointments': 'Appointments',
        'dashboard.totalProcedures': 'Total procedures performed',
        'dashboard.clinics': 'Registered Clinics',
        'dashboard.activePartners': 'Active partners',
        'dashboard.averageTicket': 'Average Ticket',
        'dashboard.perAppointment': 'Per appointment',
        'dashboard.weeklyProductivity': 'Weekly Productivity',
        'dashboard.finishedVsPending': 'Finished vs pending appointments',
        'dashboard.clinicRanking': 'Clinic Ranking',
        'dashboard.byRevenue': 'Sorted by revenue',
        'dashboard.viewAll': 'View all',
        'dashboard.newAppointment': 'New Appointment',
        'dashboard.export': 'Export',
        'dashboard.finished': 'Finished',
        
        // Appointments
        'appointments.title': 'Appointments',
        'appointments.subtitle': 'Manage your procedures and appointments.',
        'appointments.newAppointment': 'New Appointment',
        'appointments.editAppointment': 'Edit Appointment',
        'appointments.totalReceived': 'Total Received',
        'appointments.pendingValue': 'Pending Value',
        'appointments.totalAppointments': 'Total Appointments',
        'appointments.filterAll': 'All',
        'appointments.filterPaid': 'Paid',
        'appointments.filterPending': 'Pending',
        'appointments.filterScheduled': 'Scheduled',
        'appointments.searchPlaceholder': 'Search by name, clinic or procedure...',
        'appointments.patient': 'Patient',
        'appointments.procedure': 'Procedure',
        'appointments.dateTime': 'Date & Time',
        'appointments.clinic': 'Clinic',
        'appointments.value': 'Value',
        'appointments.status': 'Status',
        'appointments.paid': 'Paid',
        'appointments.pending': 'Pending',
        'appointments.scheduled': 'Scheduled',
        'appointments.unknown': 'Unknown',
        'appointments.noAppointments': 'No appointments found',
        'appointments.tryFilters': 'Try adjusting the filters or create a new appointment.',
        'appointments.clinicRequired': 'Clinic *',
        'appointments.selectClinic': 'Select a clinic',
        'appointments.appointmentDate': 'Appointment Date',
        'appointments.time': 'Time *',
        'appointments.patientName': 'Patient Name *',
        'appointments.phone': 'Phone',
        'appointments.email': 'E-mail',
        'appointments.procedureRequired': 'Procedure *',
        'appointments.selectProcedure': 'Select a procedure',
        'appointments.other': 'Other',
        'appointments.specifyProcedure': 'Specify the procedure *',
        'appointments.procedurePlaceholder': 'Enter the procedure name',
        'appointments.procedureAutoSave': 'This procedure will be automatically saved for future use.',
        'appointments.valueRequired': 'Value *',
        'appointments.currency': 'Currency',
        'appointments.paymentType': 'Payment Type',
        'appointments.percentage': 'Percentage (%)',
        'appointments.totalValue': 'Total Value:',
        'appointments.percentageValue': 'Percentage:',
        'appointments.amountToReceive': 'Amount to Receive:',
        'appointments.paymentMade': 'Payment made?',
        'appointments.paymentDate': 'Payment Date *',
        'appointments.paymentDateHint': '(When the money was received)',
        'appointments.paymentDateExample': 'Ex: If the appointment was in January but payment came in February (day 10), enter the February date here.',
        'appointments.clinicalEvolution': 'Clinical Evolution',
        'appointments.clinicalEvolutionPlaceholder': 'Describe the patient\'s clinical evolution...',
        'appointments.notes': 'Notes',
        'appointments.notesPlaceholder': 'Additional notes...',
        'appointments.radiographs': 'Radiographs',
        'appointments.uploadRadiographs': 'Click to upload radiographs',
        'appointments.selectFiles': 'Select Files',
        'appointments.uploading': 'Uploading...',
        'appointments.filesSelected': 'file(s) selected:',
        'appointments.remove': 'Remove',
        'appointments.saveAppointment': 'Save Appointment',
        'appointments.saveChanges': 'Save Changes',
        'appointments.cancel': 'Cancel',
        'appointments.deleteConfirm': 'Are you sure you want to delete this appointment?',
        'appointments.deleteSuccess': 'Appointment deleted successfully!',
        'appointments.saveSuccess': 'Appointment saved successfully!',
        'appointments.saveError': 'Error saving appointment',
        'appointments.deleteError': 'Error deleting appointment',
        'appointments.invalidImage': 'is not a valid image.',
        'appointments.fileTooLarge': 'is too large (max: 10MB).',
        'appointments.filesSelectedSuccess': 'file(s) selected successfully!',
        'appointments.processFilesError': 'Error processing files',
        'appointments.radiographsError': 'Appointment saved, but there was an error saving some radiographs',
        'appointments.procedureError': 'Error creating procedure. Using the entered name.',
        'appointments.received': 'Received:',
        
        // Patients
        'patients.title': 'Patients',
        'patients.subtitle': 'Manage your patients and history.',
        'patients.newPatient': 'New Patient',
        'patients.totalPatients': 'Total Patients',
        'patients.totalAppointments': 'Total Appointments',
        'patients.foundRecords': 'Found Records',
        'patients.searchPlaceholder': 'Search by name, email or phone...',
        'patients.lastVisit': 'Last visit',
        'patients.noPatients': 'No patients found',
        'patients.trySearch': 'Try a different search or register a new patient.',
        'patients.loading': 'Loading patients...',
        'patients.fullName': 'Full Name *',
        'patients.email': 'E-mail',
        'patients.phone': 'Phone',
        'patients.savePatient': 'Save Patient',
        'patients.createError': 'Error creating patient',
        
        // Clinics
        'clinics.title': 'Clinics',
        'clinics.subtitle': 'Manage your partner clinics.',
        'clinics.newClinic': 'New Clinic',
        'clinics.editClinic': 'Edit Clinic',
        'clinics.totalClinics': 'Total Clinics',
        'clinics.activeClinics': 'Active Clinics',
        'clinics.totalRevenue': 'Total Revenue',
        'clinics.searchPlaceholder': 'Search clinic...',
        'clinics.name': 'Name',
        'clinics.nameRequired': 'Name *',
        'clinics.address': 'Address',
        'clinics.contact': 'Contact',
        'clinics.phone': 'Phone',
        'clinics.email': 'E-mail',
        'clinics.status': 'Status',
        'clinics.active': 'Active',
        'clinics.inactive': 'Inactive',
        'clinics.noClinics': 'No clinics found',
        'clinics.trySearch': 'Try a different search or register a new clinic.',
        'clinics.loading': 'Loading clinics...',
        'clinics.saveClinic': 'Save Clinic',
        'clinics.saveChanges': 'Save Changes',
        'clinics.cancel': 'Cancel',
        'clinics.deleteConfirm': 'Are you sure you want to delete this clinic?',
        'clinics.saveError': 'Error saving clinic',
        'clinics.deleteError': 'Error deleting clinic',
        'clinics.appointments': 'Appointments',
        'clinics.totalAppointments': 'Total Appointments',
        'clinics.averageTicket': 'General Average Ticket',
        'clinics.ticket': 'Ticket:',
        'clinics.ticketAverage': 'Average Ticket',
        'clinics.registerNew': 'Register a new clinic to get started.',
        'clinics.clinicName': 'Clinic Name',
        'clinics.clinicNameExample': 'Ex: Smile Clinic',
        'clinics.addressPlaceholder': 'Street, Number, City',
        'clinics.edit': 'Edit',
        'clinics.delete': 'Delete',
        
        // Reports
        'reports.title': 'Reports',
        'reports.subtitle': 'Financial and productivity analysis',
        'reports.exportPDF': 'Export PDF',
        'reports.revenueReceived': '💰 Revenue Received',
        'reports.servicesRendered': '📅 Services Rendered',
        'reports.receivedInPeriod': '💰 Received in period',
        'reports.renderedInPeriod': '📅 Rendered in period',
        'reports.averageTicket': 'Average Ticket',
        'reports.perAppointment': 'Per appointment',
        'reports.totalAppointments': 'Total Appointments',
        'reports.receivedVsPending': 'Received vs. Pending',
        'reports.comparativeValues': 'Comparative values in the period',
        'reports.clinicDistribution': 'Clinic Distribution',
        'reports.percentageAndValues': 'Percentage and billed values',
        'reports.recentAppointments': 'Recent Appointments',
        'reports.lastProcedures': 'Last procedures performed',
        'reports.noAppointments': 'No appointments found in the selected period.',
        'reports.loading': 'Loading...',
        'reports.period': 'Period:',
        'reports.last7Days': 'Last 7 days',
        'reports.currentMonth': 'Current month',
        'reports.lastMonth': 'Last month',
        'reports.customPeriod': 'Custom period',
        'reports.byAppointmentDate': '📅 By Appointment Date',
        'reports.byPaymentDate': '💰 By Payment Date',
        'reports.startDate': 'Start Date',
        'reports.endDate': 'End Date',
        'reports.applyPeriod': 'Apply Period',
        'reports.selectDates': 'Please select the start and end dates.',
        'reports.monthsAgo': 'months ago',
        'reports.date': 'Date',
        'reports.patient': 'Patient',
        'reports.clinic': 'Clinic',
        'reports.status': 'Status',
        'reports.value': 'Value',
        'reports.noPatient': 'No patient',
        'reports.noClinic': 'No clinic',
        
        // Profile
        'profile.title': 'Profile and Settings',
        'profile.subtitle': 'Manage your account and preferences',
        'profile.activePlan': 'Active Plan',
        'profile.signOut': 'Sign Out',
        'profile.personalInfo': 'Personal Information',
        'profile.fullName': 'Full Name',
        'profile.email': 'E-mail',
        'profile.phone': 'Phone',
        'profile.saveChanges': 'Save Changes',
        'profile.preferences': 'Preferences',
        'profile.language': 'Language',
        'profile.currency': 'Currency',
        'profile.theme': 'Theme',
        'profile.darkMode': 'Dark Mode',
        'profile.lightMode': 'Light Mode',
        'profile.autoMode': 'Automatic',
        'profile.darkModeDescription': 'Interface with dark colors',
        'profile.lightModeDescription': 'Interface with light colors',
        'profile.autoModeDescription': 'Follows system/browser preference',
        'profile.savePreferences': 'Save Preferences',
        
        // Login
        'login.title': 'Welcome back!',
        'login.subtitle': 'Sign in to your account to continue',
        'login.email': 'E-mail',
        'login.password': 'Password',
        'login.signIn': 'Sign In',
        'login.forgotPassword': 'Forgot your password?',
        
        // Errors and Alerts
        'error.generic': 'An error occurred',
        'error.save': 'Error saving',
        'error.delete': 'Error deleting',
        'error.load': 'Error loading',
        'error.create': 'Error creating',
        'error.update': 'Error updating',
        'error.unauthorized': 'User not authenticated',
        'error.notFound': 'Record not found',
        'error.network': 'Connection error. Check your internet.',
        'error.fileUpload': 'Error uploading file',
        'error.fileTooLarge': 'File too large',
        'error.invalidFile': 'Invalid file',
        'error.invalidImage': 'Please select only image files.',
        'error.maxFileSize': 'The file is too large. Maximum size: 10MB.',
        'error.processingFile': 'Error processing file',
        'error.deleteConfirm': 'Are you sure you want to delete?',
        'error.deletePatientConfirm': 'Are you sure you want to delete this patient? All related appointments will also be deleted.',
        'error.deleteRadiographConfirm': 'Are you sure you want to delete this radiograph?',
        'success.save': 'Saved successfully!',
        'success.delete': 'Deleted successfully!',
        'success.create': 'Created successfully!',
        'success.update': 'Updated successfully!',
        'success.upload': 'Upload completed successfully!',
        'success.settingsSaved': 'Settings saved successfully!',
    },
    'es-ES': {
        // Common
        'common.save': 'Guardar',
        'common.cancel': 'Cancelar',
        'common.delete': 'Eliminar',
        'common.edit': 'Editar',
        'common.search': 'Buscar',
        'common.loading': 'Cargando...',
        'common.saving': 'Guardando...',
        'common.close': 'Cerrar',
        'common.confirm': 'Confirmar',
        'common.yes': 'Sí',
        'common.no': 'No',
        
        // Navigation
        'nav.dashboard': 'Panel',
        'nav.appointments': 'Citas',
        'nav.patients': 'Pacientes',
        'nav.clinics': 'Clínicas',
        'nav.reports': 'Informes',
        'nav.profile': 'Perfil',
        
        // Dashboard
        'dashboard.title': 'Panel General',
        'dashboard.subtitle': 'Visión general del rendimiento de su clínica.',
        'dashboard.monthlyRevenue': 'Facturación del Mes',
        'dashboard.received': 'Recibido',
        'dashboard.pending': 'Pendiente',
        'dashboard.appointments': 'Citas',
        'dashboard.totalProcedures': 'Total de procedimientos realizados',
        'dashboard.clinics': 'Clínicas Registradas',
        'dashboard.activePartners': 'Socios activos',
        'dashboard.averageTicket': 'Ticket Promedio',
        'dashboard.perAppointment': 'Por cita',
        'dashboard.weeklyProductivity': 'Productividad Semanal',
        'dashboard.finishedVsPending': 'Citas finalizadas vs pendientes',
        'dashboard.clinicRanking': 'Ranking de Clínicas',
        'dashboard.byRevenue': 'Ordenado por facturación',
        'dashboard.viewAll': 'Ver todas',
        'dashboard.newAppointment': 'Nueva Cita',
        'dashboard.export': 'Exportar',
        'dashboard.finished': 'Finalizadas',
        
        // Appointments
        'appointments.title': 'Citas',
        'appointments.subtitle': 'Gestione sus procedimientos y citas.',
        'appointments.newAppointment': 'Nueva Cita',
        'appointments.editAppointment': 'Editar Cita',
        'appointments.totalReceived': 'Total Recibido',
        'appointments.pendingValue': 'Valor Pendiente',
        'appointments.totalAppointments': 'Total de Citas',
        'appointments.filterAll': 'Todas',
        'appointments.filterPaid': 'Pagadas',
        'appointments.filterPending': 'Pendientes',
        'appointments.filterScheduled': 'Programadas',
        'appointments.searchPlaceholder': 'Buscar por nombre, clínica o procedimiento...',
        'appointments.patient': 'Paciente',
        'appointments.procedure': 'Procedimiento',
        'appointments.dateTime': 'Fecha y Hora',
        'appointments.clinic': 'Clínica',
        'appointments.value': 'Valor',
        'appointments.status': 'Estado',
        'appointments.paid': 'Pagado',
        'appointments.pending': 'Pendiente',
        'appointments.scheduled': 'Programado',
        'appointments.unknown': 'Desconocido',
        'appointments.noAppointments': 'No se encontraron citas',
        'appointments.tryFilters': 'Intente ajustar los filtros o cree una nueva cita.',
        'appointments.clinicRequired': 'Clínica *',
        'appointments.selectClinic': 'Seleccione una clínica',
        'appointments.appointmentDate': 'Fecha de la Cita',
        'appointments.time': 'Hora *',
        'appointments.patientName': 'Nombre del Paciente *',
        'appointments.phone': 'Teléfono',
        'appointments.email': 'Correo Electrónico',
        'appointments.procedureRequired': 'Procedimiento *',
        'appointments.selectProcedure': 'Seleccione un procedimiento',
        'appointments.other': 'Otros',
        'appointments.specifyProcedure': 'Especifique el procedimiento *',
        'appointments.procedurePlaceholder': 'Ingrese el nombre del procedimiento',
        'appointments.procedureAutoSave': 'Este procedimiento se guardará automáticamente para uso futuro.',
        'appointments.valueRequired': 'Valor *',
        'appointments.currency': 'Moneda',
        'appointments.paymentType': 'Tipo de Recepción',
        'appointments.percentage': 'Porcentaje (%)',
        'appointments.totalValue': 'Valor Total:',
        'appointments.percentageValue': 'Porcentaje:',
        'appointments.amountToReceive': 'Valor a Recibir:',
        'appointments.paymentMade': '¿Pago realizado?',
        'appointments.paymentDate': 'Fecha del Pago *',
        'appointments.paymentDateHint': '(Cuando se recibió el dinero)',
        'appointments.paymentDateExample': 'Ej: Si la cita fue en enero pero el pago llegó en febrero (día 10), ingrese la fecha de febrero aquí.',
        'appointments.clinicalEvolution': 'Evolución Clínica',
        'appointments.clinicalEvolutionPlaceholder': 'Describa la evolución clínica del paciente...',
        'appointments.notes': 'Observaciones',
        'appointments.notesPlaceholder': 'Observaciones adicionales...',
        'appointments.radiographs': 'Radiografías',
        'appointments.uploadRadiographs': 'Haga clic para subir radiografías',
        'appointments.selectFiles': 'Seleccionar Archivos',
        'appointments.uploading': 'Enviando...',
        'appointments.filesSelected': 'archivo(s) seleccionado(s):',
        'appointments.remove': 'Eliminar',
        'appointments.saveAppointment': 'Guardar Cita',
        'appointments.saveChanges': 'Guardar Cambios',
        'appointments.cancel': 'Cancelar',
        'appointments.deleteConfirm': '¿Está seguro de que desea eliminar esta cita?',
        'appointments.deleteSuccess': '¡Cita eliminada con éxito!',
        'appointments.saveSuccess': '¡Cita guardada con éxito!',
        'appointments.saveError': 'Error al guardar la cita',
        'appointments.deleteError': 'Error al eliminar la cita',
        'appointments.invalidImage': 'no es una imagen válida.',
        'appointments.fileTooLarge': 'es demasiado grande (máx: 10MB).',
        'appointments.filesSelectedSuccess': '¡archivo(s) seleccionado(s) con éxito!',
        'appointments.processFilesError': 'Error al procesar archivos',
        'appointments.radiographsError': 'Cita guardada, pero hubo un error al guardar algunas radiografías',
        'appointments.procedureError': 'Error al crear procedimiento. Usando el nombre ingresado.',
        'appointments.received': 'Recibido:',
        
        // Patients
        'patients.title': 'Pacientes',
        'patients.subtitle': 'Gestione sus pacientes e historiales.',
        'patients.newPatient': 'Nuevo Paciente',
        'patients.totalPatients': 'Total de Pacientes',
        'patients.totalAppointments': 'Total de Citas',
        'patients.foundRecords': 'Registros Encontrados',
        'patients.searchPlaceholder': 'Buscar por nombre, email o teléfono...',
        'patients.lastVisit': 'Última visita',
        'patients.noPatients': 'No se encontraron pacientes',
        'patients.trySearch': 'Intente una búsqueda diferente o registre un nuevo paciente.',
        'patients.loading': 'Cargando pacientes...',
        'patients.fullName': 'Nombre Completo *',
        'patients.email': 'Correo Electrónico',
        'patients.phone': 'Teléfono',
        'patients.savePatient': 'Guardar Paciente',
        'patients.createError': 'Error al crear paciente',
        
        // Clinics
        'clinics.title': 'Clínicas',
        'clinics.subtitle': 'Gestione sus clínicas asociadas.',
        'clinics.newClinic': 'Nueva Clínica',
        'clinics.editClinic': 'Editar Clínica',
        'clinics.totalClinics': 'Total de Clínicas',
        'clinics.activeClinics': 'Clínicas Activas',
        'clinics.totalRevenue': 'Facturación Total',
        'clinics.searchPlaceholder': 'Buscar clínica...',
        'clinics.name': 'Nombre',
        'clinics.nameRequired': 'Nombre *',
        'clinics.address': 'Dirección',
        'clinics.contact': 'Contacto',
        'clinics.phone': 'Teléfono',
        'clinics.email': 'Correo Electrónico',
        'clinics.status': 'Estado',
        'clinics.active': 'Activa',
        'clinics.inactive': 'Inactiva',
        'clinics.noClinics': 'No se encontraron clínicas',
        'clinics.trySearch': 'Intente una búsqueda diferente o registre una nueva clínica.',
        'clinics.loading': 'Cargando clínicas...',
        'clinics.saveClinic': 'Guardar Clínica',
        'clinics.saveChanges': 'Guardar Cambios',
        'clinics.cancel': 'Cancelar',
        'clinics.deleteConfirm': '¿Está seguro de que desea eliminar esta clínica?',
        'clinics.saveError': 'Error al guardar la clínica',
        'clinics.deleteError': 'Error al eliminar la clínica',
        'clinics.appointments': 'Citas',
        'clinics.totalAppointments': 'Total de Citas',
        'clinics.averageTicket': 'Ticket Promedio General',
        'clinics.ticket': 'Ticket:',
        'clinics.ticketAverage': 'Ticket Promedio',
        'clinics.registerNew': 'Registre una nueva clínica para comenzar.',
        'clinics.clinicName': 'Nombre de la Clínica',
        'clinics.clinicNameExample': 'Ej: Clínica Sonrisa',
        'clinics.addressPlaceholder': 'Calle, Número, Ciudad',
        'clinics.edit': 'Editar',
        'clinics.delete': 'Eliminar',
        
        // Reports
        'reports.title': 'Informes',
        'reports.subtitle': 'Análisis financiero y de productividad',
        'reports.exportPDF': 'Exportar PDF',
        'reports.revenueReceived': '💰 Ingresos Recibidos',
        'reports.servicesRendered': '📅 Servicios Prestados',
        'reports.receivedInPeriod': '💰 Recibido en el período',
        'reports.renderedInPeriod': '📅 Prestado en el período',
        'reports.averageTicket': 'Ticket Promedio',
        'reports.perAppointment': 'Por cita',
        'reports.totalAppointments': 'Total de Citas',
        'reports.receivedVsPending': 'Recibido vs. Pendiente',
        'reports.comparativeValues': 'Valores comparativos en el período',
        'reports.clinicDistribution': 'Distribución por Clínica',
        'reports.percentageAndValues': 'Porcentaje y valores facturados',
        'reports.recentAppointments': 'Citas Recientes',
        'reports.lastProcedures': 'Últimos procedimientos realizados',
        'reports.noAppointments': 'No se encontraron citas en el período seleccionado.',
        
        // Profile
        'profile.title': 'Perfil y Configuración',
        'profile.subtitle': 'Gestione su cuenta y preferencias',
        'profile.activePlan': 'Plan Activo',
        'profile.signOut': 'Cerrar Sesión',
        'profile.personalInfo': 'Información Personal',
        'profile.fullName': 'Nombre Completo',
        'profile.email': 'Correo Electrónico',
        'profile.phone': 'Teléfono',
        'profile.saveChanges': 'Guardar Cambios',
        'profile.preferences': 'Preferencias',
        'profile.language': 'Idioma',
        'profile.currency': 'Moneda',
        'profile.theme': 'Tema',
        'profile.darkMode': 'Modo Oscuro',
        'profile.lightMode': 'Modo Claro',
        'profile.autoMode': 'Automático',
        'profile.darkModeDescription': 'Interfaz con colores oscuros',
        'profile.lightModeDescription': 'Interfaz con colores claros',
        'profile.autoModeDescription': 'Sigue la preferencia del sistema/navegador',
        'profile.savePreferences': 'Guardar Preferencias',
        
        // Login
        'login.title': '¡Bienvenido de nuevo!',
        'login.subtitle': 'Inicie sesión en su cuenta para continuar',
        'login.email': 'Correo Electrónico',
        'login.password': 'Contraseña',
        'login.signIn': 'Iniciar Sesión',
        'login.forgotPassword': '¿Olvidó su contraseña?',
        
        // Errors and Alerts
        'error.generic': 'Ocurrió un error',
        'error.save': 'Error al guardar',
        'error.delete': 'Error al eliminar',
        'error.load': 'Error al cargar',
        'error.create': 'Error al crear',
        'error.update': 'Error al actualizar',
        'error.unauthorized': 'Usuario no autenticado',
        'error.notFound': 'Registro no encontrado',
        'error.network': 'Error de conexión. Verifique su internet.',
        'error.fileUpload': 'Error al subir el archivo',
        'error.fileTooLarge': 'Archivo demasiado grande',
        'error.invalidFile': 'Archivo inválido',
        'error.invalidImage': 'Por favor, seleccione solo archivos de imagen.',
        'error.maxFileSize': 'El archivo es demasiado grande. Tamaño máximo: 10MB.',
        'error.processingFile': 'Error al procesar archivo',
        'error.deleteConfirm': '¿Está seguro de que desea eliminar?',
        'error.deletePatientConfirm': '¿Está seguro de que desea eliminar este paciente? Todas las citas relacionadas también serán eliminadas.',
        'error.deleteRadiographConfirm': '¿Está seguro de que desea eliminar esta radiografía?',
        'success.save': '¡Guardado con éxito!',
        'success.delete': '¡Eliminado con éxito!',
        'success.create': '¡Creado con éxito!',
        'success.update': '¡Actualizado con éxito!',
        'success.upload': '¡Subida completada con éxito!',
        'success.settingsSaved': '¡Configuraciones guardadas con éxito!',
    }
};

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState(() => {
        // Try to get from localStorage first
        const savedLanguage = localStorage.getItem('language');
        return savedLanguage || 'pt-BR';
    });
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        const loadLanguage = async () => {
            // Try to get user from auth state
            try {
                const { supabase } = await import('../lib/supabaseClient');
                const { data: { session } } = await supabase.auth.getSession();
                const user = session?.user;
                
                if (user?.id) {
                    try {
                        const profile = await getUserProfile(user.id);
                        if (profile?.language) {
                            setLanguage(profile.language);
                            localStorage.setItem('language', profile.language);
                        }
                    } catch (error) {
                        console.error('Error loading language:', error);
                    }
                }
            } catch (error) {
                console.error('Error getting session:', error);
            }
            setLoading(false);
        };

        loadLanguage();
    }, []);

    const changeLanguage = async (newLanguage) => {
        setLanguage(newLanguage);
        localStorage.setItem('language', newLanguage);
        
        // Save to user profile if user is logged in
        try {
            const { supabase } = await import('../lib/supabaseClient');
            const { data: { session } } = await supabase.auth.getSession();
            const user = session?.user;
            
            if (user?.id) {
                try {
                    await updateUserProfile(user.id, { language: newLanguage });
                } catch (error) {
                    console.error('Error saving language:', error);
                }
            }
        } catch (error) {
            console.error('Error getting session:', error);
        }
    };

    const t = (key) => {
        return translations[language]?.[key] || translations['pt-BR'][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, changeLanguage, t, loading }}>
            {!loading && children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);

